title: My Jekyll Site
description: A GitHub Pages site powered by Jekyll
baseurl: "/docs"  # Since it's inside 'docs/' folder
url: "https://github.com/NShravanReddy/DeepLearning.git"  # Your repo URL
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
