name: Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Fixes "No URL found for submodule" error

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll and Dependencies
        run: |
          cd docs  # Move into the 'docs' folder where Jekyll files exist
          bundle install || bundle update  # Uses Gemfile inside 'docs/'

      - name: Build Jekyll Site
        run: |
          cd docs
          jekyll build -d ../_site  # Builds site into root '_site'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site  # The built Jekyll site
